### PR TITLE
Update to use carto.com endpoints (fix #56)

### LINKED ISSUE #56: Update to use carto.com endpoints

### PR DESCRIPTION
**Pull request by dario1985**

### CODE REVIEW

**Comment by nerik** [comment]
@AbelVM @ramiroaznar @jsanz ?

**Comment by dario1985** [comment]
@nerik @jsanz Currently the library is completely useless without this fix (1 month waiting....), because every request ends with a 404 "user not found" error.

Please, can you review this PR endpoint change or fix the problem server/dns side?

**Comment by mikegiddens** [comment]
This would be really great if someone can accept this and update this npm module to v0.5.2.  We are finding this to be an issue still with enterprise customers and would love to be able to npm install without running into this issue.

**Comment by jsanz** [comment]
Ey I want to unblock this. @dario1985 at CARTO we have a [CLA process](https://carto.com/contributions) so you should pass through that before being able to accept it. If you haven't signed it (sorry I don't have access to the records) and since it's a so trivial PR I think what we can do is to reject it and @nerik (or me, happy to help) can create a new one and merge it right away so @nerik can push it to NPM.

I understand @nerik you have admin rights on the [`cartodb` package](https://www.npmjs.com/package/cartodb/access) right?

**Comment by dario1985** [comment]
@jsanz What qualifies it as an obvious fix? BTW I close the PR and I will continue to use my fork. 
Sadly as "official" library it should work, but it doesn't.

**Comment by jsanz** [comment]
Replacing "cartodb" by "carto" on three URLs is an obvious fix. In any
case, thanks for your efforts, we'll try to update the SDK as soon as
possible.

**Pull request closed without merging**
